[book]
title = "The Book of Secret Knowledge"
authors = ["trimstray and contributors"]
language = "en"
description = "A collection of inspiring lists, manuals, cheatsheets, blogs, hacks, one-liners, cli/web tools, and more."

[output.html]
theme = "."
"default-theme" = "rust"
smart-punctuation = true
no-section-label = false

[output.html.search]
enable = true
limit-results = 100
use-boolean-and = true

[output.html.fold]
enable = true
level = 2